M48
; DRILL file {KiCad 7.0.7} date Mon Dec  4 17:46:45 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-04T17:46:45+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.236Y-54.356
X110.236Y-146.304
X202.184Y-54.356
X202.184Y-146.304
T0
M30
